### ISSUE TITLE
is capture_ supposed to work with forkIO?

### ISSUE THREAD

**Issue by pakanek** [hspec/silently#27]
Hello, is this expected output?
```
module Main (main) where

import System.IO.Silently
import Control.Concurrent

f :: IO ()
f = putStrLn "output"

main :: IO ()
main = do
  out1 <- capture_ $ forkIO f
  out2 <- capture_ f
  threadDelay (3 * 1000000)
  putStrLn $ "forkIO: '" <> out1 <> "'"
  putStrLn $ "direct: '" <> out2 <> "'"

$ stack run
output
forkIO: ''
direct: 'output
'
```

**Comment by sol** [comment]
1. When you have a shared resource such as a file descriptor[^1], and you access that shared resource concurrently without synchronization, then you can run into race conditions. That's true in general, independent of any specific libraries you use, independent of the type of resource, and independent of the used programming language.
2. Your specific example program behaves as expected. You are not observing a race condition. Did you mean `forkIO $ capture_ f` instead of `capture_ $ forkIO f`?
3. While ChatGPT has a tendency to hallucinate (e.g. don't try to ask ChatGPT for a solution to your problem), it does a good job in explaining what's going on with your particular program.

### This is what ChatGPT has to say about your program:

The output you are getting is expected based on how `forkIO` and `capture_` work together. Here's a detailed explanation:

1. **forkIO**: This function spawns a new lightweight thread to run the given `IO` action. The main thread does not wait for the forked thread to complete; they run concurrently.

2. **capture_**: This function captures any output (stdout) produced by an `IO` action. When used with `forkIO`, it captures the output of the main thread, but not the forked thread because `capture_` completes before the forked thread does its printing.

4. **threadDelay**: This causes the main thread to pause, giving time for the forked thread to complete its execution.

In your code:

- `out1 <- capture_ $ forkIO f` captures the output of the main thread, which includes the action of forking a new thread but not the output of the forked thread itself. Hence, `out1` is empty.
- `out2 <- capture_ f` captures the output of the direct execution of `f`, which is "output".

Thus, the resulting output:

```
output
forkIO: ''
direct: 'output
'
```

makes sense because:
- "output" is printed directly by the forked thread.
- `forkIO: ''` shows that `out1` is empty since the output of the forked thread was not captured.
- `direct: 'output\n'` shows the captured output of the direct call to `f`.

If you need the output from `forkIO` to be captured, you would need to use a different approach, possibly involving synchronization primitives like `MVar` or `Chan` to capture and synchronize outputs between threads.



[^1]: Note that `stdout` is a file descriptor and that `capture_` captures `stdout`.

**Comment by pakanek** [comment]
That makes sense, thanks a lot. Should be something like 
```
v <- newEmptyMVar
forkIO $ capture_ f >>= putMVar v
out1 <- readMVar v
```
